### ISSUE TITLE
Styling of the textfields

### ISSUE THREAD

**Issue by pedronim** [vaadin-component-factory/vcf-date-range-picker-flow#9]
I tried the component when there is very little space for it:

<img width="243" alt="Screenshot 2021-05-20 at 10 34 39" src="https://user-images.githubusercontent.com/4959788/118957949-407f8f80-b961-11eb-82a6-651af5ea4c7d.png">

and without clear buttons

<img width="233" alt="Screenshot 2021-05-20 at 12 12 46" src="https://user-images.githubusercontent.com/4959788/118961591-c2bd8300-b964-11eb-932c-832239ab450a.png">

I'm aware that it is almost impossible to have a daterange in this amount of space, but I think the current date range textfield can be improved:

1. Removing the clear button from both fields will already help some. There is issue https://github.com/vaadin-component-factory/vcf-date-range-picker-flow/issues/7 for this already.
2. I'm missing a dash between the two textfields. It would help understand that this is a range field, I think.
3. I think there is some padding at the end of the start date field and the start of the end date field that could be used to place the dash in. So, something like this: <img width="233" alt="Screenshot 2021-05-20 at 12 12 46" src="https://user-images.githubusercontent.com/4959788/118962080-4a0af680-b965-11eb-9d39-39c2079c3c9f.png">

I first thought it could be possible to have the start date textfield resize according to the width of the selected date (instead of it being "width: 50%", but I guess that's quite difficult to do, right? This would help the problem when there is little space, so I'm throwing it out there anyways...

**Comment by mlopezFC** [comment]
Hi! ... after struggling a lot, this is the best that I could achieve:
![image](https://user-images.githubusercontent.com/28312758/119714217-fc94fa80-be38-11eb-8087-a3c3e545d157.png)
The problem with this approach is that I had to make the first textfield to occupy less space compared with the other (45%-55%), taking into account that the second textfield already contains the calendar button, so it has to be bigger. And the problem is that when it's bigger, then the dash is not exactly in the middle:
![image](https://user-images.githubusercontent.com/28312758/119715700-a923ac00-be3a-11eb-9416-d7a02f9e921e.png)
Then there is another problem when adding the clear button, because in that case the size of the first textfield should be even smaller.
I'm not sure if it's possible to achieve that the textfield automatically changes it size according to the selected date, I will investigate that and let you know.
